### ISSUE TITLE
Work with Node 0.6 too?

### ISSUE THREAD

**Issue by aseemk** [coffeedoc/codo#59]
Hey there,

Great work on this library and tool. I'd love to use it for my projects, but a few of them are still on Node 0.6 for the time being since they're big and upgrading will require a bit of time.

It seems that Codo should work fine on Node 0.6 (the package.json says >= 0.4), but right off the bat in `codo.coffee`, the `fs.existsSync` call fails. (It should probably be `fs.existsSync || path.existsSync` for backwards-compatibility.)

But even after changing that, it fails with a cryptic error that I haven't been able to debug:

```
Cannot generate documentation: undefined is not a function
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/codo/node_modules/async/lib/async.js:229:13
    at /usr/local/lib/node_modules/codo/node_modules/async/lib/async.js:86:13
    at Array.forEach (native)
    at /usr/local/lib/node_modules/codo/node_modules/async/lib/async.js:26:24
    at /usr/local/lib/node_modules/codo/node_modules/async/lib/async.js:85:9
    at /usr/local/lib/node_modules/codo/node_modules/async/lib/async.js:228:9
    at Object.<anonymous> (/usr/local/lib/node_modules/codo/node_modules/async/lib/async.js:168:23)
    at Object.inputs (/usr/local/lib/node_modules/codo/src/codo.coffee:194:20)
    at /usr/local/lib/node_modules/codo/node_modules/async/lib/async.js:467:24
    at /usr/local/lib/node_modules/codo/node_modules/async/lib/async.js:86:13
```

I'm on Node 0.6.16 and Codo 1.3.0 FWIW.

If this is too much trouble, I understand. But if not, it'd be great to be able to use this. =) Thanks for the consideration! And great work again.

Cheers,
Aseem
